### ISSUE TITLE
Inquiry about AutoPT 

### ISSUE THREAD

**Issue by Azziz-77** [Dizzy-K/AutoPT#1]
Hello,

Thank you for sharing the AutoPT project on GitHub. I am currently exploring your project to develop an automated red team platform, and I find it highly inspiring and relevant to my work.

I have been trying to set up and run the tool but have encountered some challenges. Here is what I’ve done so far:

Installed the requirements from requirements.txt and set up the API keys.
Ran the Docker image for the Drupal vulnerability to test the tool.
However, I’m facing some issues, such as:

SSH-related functionality in terminal.py that doesn’t seem compatible with the Docker environment.
Errors persisting even after I modified parts of the code to bypass SSH.
I would greatly appreciate it if you could share any general guidance or steps on how to successfully set up and run the tool.

**Comment by Dizzy-K** [comment]
Thank you for your attention. Terminal.py is used to connect to attack docker (such as Kali-Linux). 
Our work is currently under peer review. After the review is accepted, complete instructions and samples will be provided.
